# Generated by Django 4.0 on 2022-01-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='parrent',
            new_name='parent',
        ),
    ]
